import type * as OpenAPIV3_2 from '@openapi-spec/types/v3.2'

// A document generated by `OpenAPIGenerator` from @orpc/openapi
// 2.0.0-beta.41 with `ZodToJsonSchemaConverter` from @orpc/zod and zod 4,
// before any downgrade. oRPC always generates 3.2 and downgrades when an
// older version is asked for, so this is what both converters see from it.
//
// The router covers what oRPC emits: path, query (deepObject, comma-delimited),
// header, and body inputs; JSON, multipart, file, and event-stream bodies;
// detailed outputs with response headers; typed errors; and schemas with
// nullable fields, tuples, sets, maps, records, dates, bigints, enums,
// numeric exclusive bounds, examples, registry components, and recursion.
export const doc: OpenAPIV3_2.OpenAPIObject = {
  info: {
    title: 'Planets',
    version: '1.0.0',
    summary: 'Planets and their categories',
  },
  servers: [
    {
      url: 'https://api.example.com',
      name: 'production',
    },
  ],
  tags: [
    {
      name: 'planets',
      summary: 'Planets',
      kind: 'nav',
    },
  ],
  components: {
    securitySchemes: {
      bearer: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
    schemas: {
      Planet: {
        type: 'object',
        properties: {
          id: {
            type: 'string',
            format: 'uuid',
            pattern: '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
          },
          name: {
            type: 'string',
            minLength: 1,
            description: 'The planet name',
          },
          description: {
            type: [
              'string',
              'null',
            ],
          },
          mass: {
            type: 'number',
            exclusiveMinimum: 0,
            examples: [
              5.97e+24,
            ],
          },
          moons: {
            type: 'integer',
            minimum: 0,
            maximum: 9007199254740991,
          },
          kind: {
            type: 'string',
            enum: [
              'rocky',
              'gas',
              'ice',
            ],
          },
          discoveredAt: {
            'type': 'string',
            'format': 'date-time',
            'x-native-type': 'date',
          },
          position: {
            type: 'array',
            prefixItems: [
              {
                type: 'number',
              },
              {
                type: 'number',
              },
              {
                type: 'number',
              },
            ],
            items: false,
            minItems: 3,
            maxItems: 3,
          },
          tags: {
            'type': 'array',
            'uniqueItems': true,
            'items': {
              type: 'string',
            },
            'x-native-type': 'set',
          },
          aliases: {
            'type': 'array',
            'items': {
              type: 'array',
              prefixItems: [
                {
                  type: 'string',
                },
                {
                  type: 'string',
                },
              ],
              maxItems: 2,
              minItems: 2,
            },
            'x-native-type': 'map',
          },
          attributes: {
            type: 'object',
            propertyNames: {
              type: 'string',
            },
            additionalProperties: {
              type: [
                'string',
                'number',
                'boolean',
              ],
            },
          },
          population: {
            'type': 'string',
            'pattern': '^-?[0-9]+$',
            'x-native-type': 'bigint',
          },
        },
        required: [
          'id',
          'name',
          'description',
          'mass',
          'kind',
          'discoveredAt',
          'position',
          'tags',
          'aliases',
          'attributes',
        ],
        additionalProperties: false,
      },
      UndefinedError: {
        title: 'UndefinedError',
        type: 'object',
        properties: {
          defined: {
            const: false,
          },
          code: {
            type: 'string',
          },
          message: {
            type: 'string',
          },
          data: {},
        },
        required: [
          'defined',
          'code',
          'message',
        ],
      },
      NotFound: {
        title: 'NOT_FOUND',
        type: 'object',
        properties: {
          defined: {
            const: true,
          },
          code: {
            const: 'NOT_FOUND',
          },
          message: {
            type: 'string',
          },
          data: {
            type: 'object',
            properties: {
              id: {
                type: 'string',
              },
            },
            required: [
              'id',
            ],
            additionalProperties: false,
          },
        },
        required: [
          'defined',
          'code',
          'message',
          'data',
        ],
      },
      Conflict: {
        title: 'CONFLICT',
        type: 'object',
        properties: {
          defined: {
            const: true,
          },
          code: {
            const: 'CONFLICT',
          },
          message: {
            type: 'string',
          },
          data: {},
        },
        required: [
          'defined',
          'code',
          'message',
        ],
      },
      BadRequest: {
        title: 'BAD_REQUEST',
        type: 'object',
        properties: {
          defined: {
            const: true,
          },
          code: {
            const: 'BAD_REQUEST',
          },
          message: {
            type: 'string',
          },
          data: {
            type: 'object',
            properties: {
              issues: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    path: {
                      type: 'array',
                      items: {
                        type: [
                          'string',
                          'number',
                        ],
                      },
                    },
                    message: {
                      type: 'string',
                    },
                  },
                  required: [
                    'path',
                    'message',
                  ],
                  additionalProperties: false,
                },
              },
            },
            required: [
              'issues',
            ],
            additionalProperties: false,
          },
        },
        required: [
          'defined',
          'code',
          'message',
          'data',
        ],
      },
      Category: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
          },
          parent: {
            anyOf: [
              {
                $ref: '#/components/schemas/Category',
              },
              {
                type: 'null',
              },
            ],
          },
          children: {
            type: 'array',
            items: {
              $ref: '#/components/schemas/Category',
            },
          },
        },
        required: [
          'name',
          'parent',
          'children',
        ],
        additionalProperties: false,
      },
    },
  },
  security: [
    {
      bearer: [],
    },
  ],
  openapi: '3.2.0',
  paths: {
    '/planets': {
      get: {
        operationId: 'planets.list',
        summary: 'List planets',
        tags: [
          'planets',
        ],
        parameters: [
          {
            in: 'query',
            name: 'limit',
            schema: {
              default: 20,
              type: 'integer',
              minimum: 1,
              maximum: 100,
            },
            allowEmptyValue: true,
            allowReserved: true,
          },
          {
            in: 'query',
            name: 'cursor',
            schema: {
              type: 'string',
            },
            allowEmptyValue: true,
            allowReserved: true,
          },
          {
            in: 'query',
            name: 'filter',
            schema: {
              type: 'object',
              properties: {
                kind: {
                  type: 'string',
                  enum: [
                    'rocky',
                    'gas',
                    'ice',
                  ],
                },
                name: {
                  type: 'string',
                },
              },
            },
            allowEmptyValue: true,
            allowReserved: true,
            style: 'deepObject',
            explode: true,
          },
          {
            in: 'query',
            name: 'ids',
            schema: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            allowEmptyValue: true,
            allowReserved: true,
            style: 'deepObject',
            explode: true,
          },
        ],
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    items: {
                      type: 'array',
                      items: {
                        $ref: '#/components/schemas/Planet',
                      },
                    },
                    next: {
                      type: [
                        'string',
                        'null',
                      ],
                    },
                  },
                  required: [
                    'items',
                    'next',
                  ],
                  additionalProperties: false,
                },
              },
            },
          },
        },
      },
      post: {
        operationId: 'planets.create',
        deprecated: true,
        tags: [
          'planets',
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  name: {
                    type: 'string',
                    minLength: 1,
                    description: 'The planet name',
                  },
                  description: {
                    type: [
                      'string',
                      'null',
                    ],
                  },
                  mass: {
                    type: 'number',
                    exclusiveMinimum: 0,
                    examples: [
                      5.97e+24,
                    ],
                  },
                  moons: {
                    type: 'integer',
                    minimum: 0,
                    maximum: 9007199254740991,
                  },
                  kind: {
                    type: 'string',
                    enum: [
                      'rocky',
                      'gas',
                      'ice',
                    ],
                  },
                  discoveredAt: {
                    'type': 'string',
                    'format': 'date-time',
                    'x-native-type': 'date',
                  },
                  position: {
                    type: 'array',
                    prefixItems: [
                      {
                        type: 'number',
                      },
                      {
                        type: 'number',
                      },
                      {
                        type: 'number',
                      },
                    ],
                    items: false,
                    minItems: 3,
                    maxItems: 3,
                  },
                  tags: {
                    'type': 'array',
                    'uniqueItems': true,
                    'items': {
                      type: 'string',
                    },
                    'x-native-type': 'set',
                  },
                  aliases: {
                    'type': 'array',
                    'items': {
                      type: 'array',
                      prefixItems: [
                        {
                          type: 'string',
                        },
                        {
                          type: 'string',
                        },
                      ],
                      maxItems: 2,
                      minItems: 2,
                    },
                    'x-native-type': 'map',
                  },
                  attributes: {
                    type: 'object',
                    propertyNames: {
                      type: 'string',
                    },
                    additionalProperties: {
                      type: [
                        'string',
                        'number',
                        'boolean',
                      ],
                    },
                  },
                  population: {
                    'type': 'string',
                    'pattern': '^-?[0-9]+$',
                    'x-native-type': 'bigint',
                  },
                },
                required: [
                  'name',
                  'description',
                  'mass',
                  'kind',
                  'discoveredAt',
                  'position',
                  'tags',
                  'aliases',
                  'attributes',
                ],
              },
            },
          },
        },
        responses: {
          201: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Planet',
                },
              },
            },
          },
          400: {
            description: '400',
            content: {
              'application/json': {
                schema: {
                  oneOf: [
                    {
                      $ref: '#/components/schemas/BadRequest',
                    },
                    {
                      $ref: '#/components/schemas/UndefinedError',
                    },
                  ],
                },
              },
            },
          },
          409: {
            description: '409',
            content: {
              'application/json': {
                schema: {
                  oneOf: [
                    {
                      $ref: '#/components/schemas/Conflict',
                    },
                    {
                      $ref: '#/components/schemas/UndefinedError',
                    },
                  ],
                },
              },
            },
          },
        },
      },
    },
    '/planets/{id}': {
      get: {
        operationId: 'planets.find',
        tags: [
          'planets',
        ],
        parameters: [
          {
            in: 'path',
            required: true,
            name: 'id',
            schema: {
              type: 'string',
            },
          },
          {
            in: 'query',
            name: 'fields',
            schema: {
              type: 'array',
              items: {
                type: 'string',
              },
            },
            allowEmptyValue: true,
            allowReserved: true,
            explode: false,
          },
        ],
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  anyOf: [
                    {
                      $ref: '#/components/schemas/Planet',
                    },
                    {
                      type: 'null',
                    },
                  ],
                },
              },
            },
          },
          404: {
            description: 'Planet not found',
            content: {
              'application/json': {
                schema: {
                  oneOf: [
                    {
                      $ref: '#/components/schemas/NotFound',
                    },
                    {
                      $ref: '#/components/schemas/UndefinedError',
                    },
                  ],
                },
              },
            },
          },
        },
      },
      patch: {
        operationId: 'planets.update',
        parameters: [
          {
            in: 'path',
            required: true,
            name: 'id',
            schema: {
              type: 'string',
            },
          },
          {
            in: 'query',
            name: 'dryRun',
            schema: {
              type: 'boolean',
            },
            allowEmptyValue: true,
            allowReserved: true,
          },
          {
            in: 'header',
            name: 'if-match',
            required: true,
            schema: {
              type: 'string',
            },
          },
        ],
        requestBody: {
          required: true,
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                    format: 'uuid',
                    pattern: '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$',
                  },
                  name: {
                    type: 'string',
                    minLength: 1,
                    description: 'The planet name',
                  },
                  description: {
                    type: [
                      'string',
                      'null',
                    ],
                  },
                  mass: {
                    type: 'number',
                    exclusiveMinimum: 0,
                    examples: [
                      5.97e+24,
                    ],
                  },
                  moons: {
                    type: 'integer',
                    minimum: 0,
                    maximum: 9007199254740991,
                  },
                  kind: {
                    type: 'string',
                    enum: [
                      'rocky',
                      'gas',
                      'ice',
                    ],
                  },
                  discoveredAt: {
                    'type': 'string',
                    'format': 'date-time',
                    'x-native-type': 'date',
                  },
                  position: {
                    type: 'array',
                    prefixItems: [
                      {
                        type: 'number',
                      },
                      {
                        type: 'number',
                      },
                      {
                        type: 'number',
                      },
                    ],
                    items: false,
                    minItems: 3,
                    maxItems: 3,
                  },
                  tags: {
                    'type': 'array',
                    'uniqueItems': true,
                    'items': {
                      type: 'string',
                    },
                    'x-native-type': 'set',
                  },
                  aliases: {
                    'type': 'array',
                    'items': {
                      type: 'array',
                      prefixItems: [
                        {
                          type: 'string',
                        },
                        {
                          type: 'string',
                        },
                      ],
                      maxItems: 2,
                      minItems: 2,
                    },
                    'x-native-type': 'map',
                  },
                  attributes: {
                    type: 'object',
                    propertyNames: {
                      type: 'string',
                    },
                    additionalProperties: {
                      type: [
                        'string',
                        'number',
                        'boolean',
                      ],
                    },
                  },
                  population: {
                    'type': 'string',
                    'pattern': '^-?[0-9]+$',
                    'x-native-type': 'bigint',
                  },
                },
              },
            },
          },
        },
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  $ref: '#/components/schemas/Planet',
                },
              },
            },
            headers: {
              etag: {
                required: true,
                schema: {
                  type: 'string',
                },
              },
            },
          },
          202: {
            description: 'Accepted',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    jobId: {
                      type: 'string',
                    },
                  },
                  required: [
                    'jobId',
                  ],
                  additionalProperties: false,
                },
              },
            },
          },
        },
      },
    },
    '/planets/{id}/image': {
      put: {
        operationId: 'planets.upload',
        parameters: [
          {
            in: 'path',
            required: true,
            name: 'id',
            schema: {
              type: 'string',
            },
          },
        ],
        requestBody: {
          required: true,
          content: {
            'multipart/form-data': {
              schema: {
                type: 'object',
                properties: {
                  image: {
                    type: 'string',
                    format: 'binary',
                    contentEncoding: 'binary',
                    contentMediaType: 'image/png',
                  },
                  caption: {
                    type: 'string',
                  },
                },
                required: [
                  'image',
                ],
              },
            },
          },
        },
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'object',
                  properties: {
                    url: {
                      type: 'string',
                      format: 'uri',
                    },
                  },
                  required: [
                    'url',
                  ],
                  additionalProperties: false,
                },
              },
            },
          },
        },
      },
      get: {
        operationId: 'planets.image',
        parameters: [
          {
            in: 'path',
            required: true,
            name: 'id',
            schema: {
              type: 'string',
            },
          },
        ],
        responses: {
          200: {
            description: 'OK',
            content: {
              'image/png': {
                schema: {
                  contentMediaType: 'image/png',
                  type: 'string',
                  format: 'binary',
                  contentEncoding: 'binary',
                },
              },
              'image/jpeg': {
                schema: {
                  contentMediaType: 'image/jpeg',
                  type: 'string',
                  format: 'binary',
                  contentEncoding: 'binary',
                },
              },
            },
          },
        },
      },
    },
    '/planets/events': {
      get: {
        operationId: 'planets.events',
        responses: {
          200: {
            description: 'OK',
            content: {
              'text/event-stream': {
                schema: {
                  oneOf: [
                    {
                      type: 'object',
                      properties: {
                        event: {
                          const: 'message',
                        },
                        data: {
                          type: 'object',
                          properties: {
                            type: {
                              type: 'string',
                              const: 'created',
                            },
                            planet: {
                              $ref: '#/components/schemas/Planet',
                            },
                          },
                          required: [
                            'type',
                            'planet',
                          ],
                          additionalProperties: false,
                        },
                        id: {
                          type: 'string',
                        },
                        retry: {
                          type: 'number',
                        },
                      },
                      required: [
                        'event',
                        'data',
                      ],
                    },
                    {
                      type: 'object',
                      properties: {
                        event: {
                          const: 'close',
                        },
                        data: {
                          type: 'object',
                          properties: {
                            total: {
                              type: 'number',
                            },
                          },
                          required: [
                            'total',
                          ],
                          additionalProperties: false,
                        },
                        id: {
                          type: 'string',
                        },
                        retry: {
                          type: 'number',
                        },
                      },
                      required: [
                        'event',
                        'data',
                      ],
                    },
                    {
                      type: 'object',
                      properties: {
                        event: {
                          const: 'error',
                        },
                        data: {},
                        id: {
                          type: 'string',
                        },
                        retry: {
                          type: 'number',
                        },
                      },
                      required: [
                        'event',
                      ],
                    },
                  ],
                },
              },
            },
          },
        },
      },
    },
    '/categories': {
      get: {
        operationId: 'categories',
        responses: {
          200: {
            description: 'OK',
            content: {
              'application/json': {
                schema: {
                  type: 'array',
                  items: {
                    $ref: '#/components/schemas/Category',
                  },
                },
              },
            },
          },
        },
      },
    },
    '/ping': {
      head: {
        operationId: 'ping',
        responses: {
          200: {
            description: 'OK',
            content: {},
          },
        },
      },
    },
  },
}
